# main.py (Corrected for user ID issue)

import os
import mysql.connector
import google.generativeai as genai
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from dotenv import load_dotenv

load_dotenv()

try:
    genai.configure(api_key=os.getenv("GOOGLE_API_KEY"))
    generative_model = genai.GenerativeModel('gemini-1.5-flash')
except Exception as e:
    print(f"Error configuring Google AI: {e}")
    generative_model = None

user_session_state = {}

def get_db_connection():
    try:
        conn = mysql.connector.connect(
            host=os.getenv("DB_HOST"),
            user=os.getenv("DB_USER"),
            password=os.getenv("DB_PASSWORD"),
            database=os.getenv("DB_NAME")
        )
        return conn
    except mysql.connector.Error as e:
        print(f"Error connecting to MySQL Database: {e}")
        return None

def get_mastered_skills(cursor, numeric_user_id):
    query = "SELECT skill_id FROM User_Skills WHERE user_id = %s"
    cursor.execute(query, (numeric_user_id,))
    mastered_ids = set(map(lambda row: row['skill_id'], cursor.fetchall()))
    print(f"User ID {numeric_user_id} has mastered skill IDs: {mastered_ids}")
    return mastered_ids

def find_next_skill(cursor, mastered_skills, goal_skill_id):
    if goal_skill_id in mastered_skills:
        return None
    query = "SELECT prerequisite_id FROM Prerequisites WHERE skill_id = %s"
    cursor.execute(query, (goal_skill_id,))
    prerequisites = cursor.fetchall()
    if not prerequisites:
        return goal_skill_id
    for prereq in prerequisites:
        skill_to_learn = find_next_skill(cursor, mastered_skills, prereq['prerequisite_id'])
        if skill_to_learn is not None:
            return skill_to_learn
    return goal_skill_id

app = FastAPI()
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class ChatRequest(BaseModel):
    message: str
    user_id: str # This will now be treated as a username

@app.post("/chat")
async def chat_handler(chat_request: ChatRequest):
    username = chat_request.user_id # Treat the incoming ID as a username
    user_message = chat_request.message
    ai_response = "An unexpected error occurred."

    db_connection = get_db_connection()
    if not db_connection:
        return {"reply": "Error: Could not connect to the database."}

    try:
        cursor = db_connection.cursor(dictionary=True)
        
        # --- MODIFIED USER HANDLING LOGIC ---
        # 1. Find the user by their username
        cursor.execute("SELECT user_id FROM Users WHERE username = %s", (username,))
        user_record = cursor.fetchone()
        
        if not user_record:
            # 2. If they don't exist, create them WITHOUT providing a user_id
            cursor.execute("INSERT INTO Users (username, email, password_hash) VALUES (%s, %s, %s)",
                           (username, f"{username}@example.com", "placeholder"))
            db_connection.commit()
            numeric_user_id = cursor.lastrowid # Get the new ID generated by the database
            print(f"Created new user with ID: {numeric_user_id}")
        else:
            # 3. If they exist, get their numeric ID
            numeric_user_id = user_record['user_id']

        # --- State Machine Logic (now using the correct numeric ID) ---
        if username not in user_session_state:
            mastered_skills = get_mastered_skills(cursor, numeric_user_id)
            goal_skill_id = 7
            next_skill_id = find_next_skill(cursor, mastered_skills, goal_skill_id)

            if next_skill_id:
                cursor.execute("SELECT skill_name FROM Skills WHERE skill_id = %s", (next_skill_id,))
                skill_record = cursor.fetchone()
                user_session_state[username] = {
                    "current_skill_id": next_skill_id,
                    "numeric_user_id": numeric_user_id, # Store the correct ID
                    "skill_name": skill_record['skill_name'],
                    "phase": "Crawl"
                }
                print(f"Starting new session for {username}: Learning '{skill_record['skill_name']}'")
            else:
                return {"reply": "Congratulations! You have mastered the entire Algebra path!"}

        current_session = user_session_state[username]
        skill_name = current_session['skill_name']
        phase = current_session['phase']

        system_prompt = ""
        if phase == "Crawl":
            system_prompt = f"You are a teacher. Your task is to EXPLAIN the concept of '{skill_name}'. Keep it simple and clear. End by asking if the user understands."
            user_session_state[username]['phase'] = 'Walk'
        elif phase == "Walk":
            system_prompt = f"You are a friendly tutor. The user has just learned the definition of '{skill_name}'. Your task is to GUIDE them through a simple, interactive example of it. Ask leading questions."
            user_session_state[username]['phase'] = 'Run'
        elif phase == "Run":
            system_prompt = f"You are an examiner. Assess if the user has mastered '{skill_name}'. Ask them a direct question or problem to solve. Then, analyze their answer. If their answer is correct, FINISH your response with the single word: CORRECT. Otherwise, do not use that word."
            
            if generative_model:
                full_prompt = f"{system_prompt}\n\nUSER'S ANSWER: {user_message}"
                response = generative_model.generate_content(full_prompt)
                ai_response = response.text
                
                if "CORRECT" in ai_response.upper():
                    skill_id_to_save = current_session['current_skill_id']
                    user_id_to_save = current_session['numeric_user_id']
                    # Use the correct numeric ID to save progress
                    cursor.execute("INSERT INTO User_Skills (user_id, skill_id) VALUES (%s, %s) ON DUPLICATE KEY UPDATE skill_id=skill_id", (user_id_to_save, skill_id_to_save))
                    db_connection.commit()
                    print(f"User ID {user_id_to_save} mastered skill ID: {skill_id_to_save}")
                    del user_session_state[username]
                    ai_response += "\n\nGreat job! You've mastered this topic. What's next?"
                return {"reply": ai_response}
            else:
                return {"reply": "AI model not configured."}

        if generative_model:
            full_prompt = f"{system_prompt}\n\nUSER'S PREVIOUS MESSAGE FOR CONTEXT: {user_message}"
            response = generative_model.generate_content(full_prompt)
            ai_response = response.text
        else:
            ai_response = "AI model not configured."

    except Exception as e:
        ai_response = f"An error occurred: {e}"
        print(e)
    finally:
        if db_connection and db_connection.is_connected():
            cursor.close()
            db_connection.close()

    return {"reply": ai_response}

@app.get("/")
def read_root():
    return {"message": "AI Tutor API is running!"}